### ISSUE TITLE
Response type incompatabile with pre 4.2 TypeScript, introduced in v3.1.0

### ISSUE THREAD

**Issue by xenjke** [lquixada/cross-fetch#102]
## Issue

Version 3.1.0 introduced a breaking change to `Response` type.

Up to this version, Cross-Fetch response type was matching `Response` type from [TypeScript Types](https://github.com/microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L12715)

### Example code
```typescript
import { fetch, Response as CrossFetchResponse } from 'cross-fetch';

fetch('https://www.example').then((response: Response) => {
    console.log(response);
})
```

### Compilation failure
```bash
> tsc response-compatibility.ts

response-compatibility.ts:3:35 - error TS2345: Argument of type '(response: Response) => void' is not assignable to parameter of type '(value: Response) => void | PromiseLike<void>'.
  Types of parameters 'response' and 'value' are incompatible.
    Type 'import("cross_fetch_repro/node_modules/cross-fetch/lib.fetch").Response' is not assignable to type 'Response'.
      The types returned by 'body.getReader(...).read(...)' are incompatible between these types.
        Type 'Promise<ReadableStreamDefaultReadResult<Uint8Array>>' is not assignable to type 'Promise<ReadableStreamReadResult<T>>'.
          Type 'ReadableStreamDefaultReadResult<Uint8Array>' is not assignable to type 'ReadableStreamReadResult<T>'.
            Type 'ReadableStreamDefaultReadValueResult<Uint8Array>' is not assignable to type 'ReadableStreamReadResult<T>'.
              Type 'ReadableStreamDefaultReadValueResult<Uint8Array>' is not assignable to type 'ReadableStreamReadValueResult<T>'.
                Types of property 'value' are incompatible.
                  Type 'Uint8Array' is not assignable to type 'T'.
                    'Uint8Array' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'ArrayBufferView'.

3 fetch('https://www.example.com').then((response: Response) => {
```

Same example compiles fine with `cross-fetch` locked to 3.0.6.

## Environment

- **TypeScript**: 4.1.2. Also reproducible in 3.8.
- **NodeJS**: 14, 12, 10

**Comment by xenjke** [comment]
3.1.2 is still failing:

```bash
tsc --lib 'es2015,dom' response-compatibility.ts
```

```bash
response-compatibility.ts:3:35 - error TS2345: Argument of type '(response: Response) => Response' is not assignable to parameter of type '(value: Response) => Response | PromiseLike<Response>'.
  Types of parameters 'response' and 'value' are incompatible.
    Type 'import("/Users/ashulzhe/workspace/fetch_repro/node_modules/cross-fetch/lib.fetch").Response' is not assignable to type 'Response'.
      The types returned by 'body.getReader(...).read(...)' are incompatible between these types.
        Type 'Promise<ReadableStreamDefaultReadResult<Uint8Array>>' is not assignable to type 'Promise<ReadableStreamReadResult<T>>'.
          Type 'ReadableStreamDefaultReadResult<Uint8Array>' is not assignable to type 'ReadableStreamReadResult<T>'.
            Type 'ReadableStreamDefaultReadValueResult<Uint8Array>' is not assignable to type 'ReadableStreamReadResult<T>'.
              Type 'ReadableStreamDefaultReadValueResult<Uint8Array>' is not assignable to type 'ReadableStreamReadValueResult<T>'.
                Types of property 'value' are incompatible.
                  Type 'Uint8Array' is not assignable to type 'T'.
                    'Uint8Array' is assignable to the constraint of type 'T', but 'T' could be instantiated with a different subtype of constraint 'ArrayBufferView'.

3 fetch('https://www.example').then((response: Response) => {
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by xenjke** [comment]
Oh, just saw this: https://github.com/lquixada/cross-fetch/compare/v3.0.6...v3.1.0#diff-f7f0f95ec93e0923892ad51098f66c7979f1558a42cb798df6bf4a56c42b3ebdR1

Tried running with TS 4.2.3:

```bash
> node_modules/.bin/tsc -v
Version 4.2.3
> node_modules/.bin/tsc --lib 'dom,es2015' response-compatibility.ts
# compiles!
```

**Comment by lquixada** [comment]
@xenjke hey, thanks for reporting this issue. Can you run `npm install cross-fetch@3.1.3-alpha.6` and check if the problem persists?

**Comment by xenjke** [comment]
Hey @lquixada, thank you for the quick turnaround! I can confirm that `cross-fetch@3.1.3-alpha.6` resolved the issue for us. We'll pick the fix up from the release 👍
